Repository Codin-Nerds/HotWired-Bot, pull requests merged in 2020-06, with the labels that each got.

#1 Flake8 compatibility
  cogs/code_utils/_docs.py
  cogs/code_utils/_ref.py
  cogs/code_utils/_tio.py
  cogs/code_utils/_used.py
  cogs/codesandbox.py
  cogs/coding.py
  cogs/commands.py
  cogs/custom.py
  cogs/events.py
  cogs/fun.py
  cogs/games.py
  cogs/infog.py
  cogs/moderation.py
  cogs/sudo.py
  cogs/tools.py
  cogs/utils/constants.py
  cogs/utils/embedHandler.py
  cogs/utils/flags.py
  cogs/utils/members.py
  main.py
  utils/binarycalc.py
  utils/covidscrape.py
  utils/hexcalc.py
  utils/mathscrape.py
  utils/octcalc.py
  utils/wolframscrape.py
Labels: priority: 1 - high, status: needs review, type: feature

#10 Updates in cogs, Split code in proper categories
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  cogs/code_utils/_doc.py
  cogs/coding.py
  cogs/commands.py
  cogs/custom.py
  cogs/games.py
  cogs/study.py
  cogs/sudo.py
  cogs/support.py
  cogs/utils/__pycache__/constants.cpython-38.pyc
  cogs/utils/__pycache__/embedHandler.cpython-38.pyc
  cogs/utils/__pycache__/flags.cpython-38.pyc
  cogs/utils/__pycache__/members.cpython-38.pyc
  cogs/utils/constants.py
  flake8.cfg
  main.py
  poetry.lock
  pyproject.toml
  requirements.txt
  utils/__pycache__/covidscrape.cpython-38.pyc
  utils/__pycache__/mathscrape.cpython-38.pyc
  utils/__pycache__/wolframscrape.cpython-38.pyc
  utils/covidscrape.py
  utils/wolframscrape.py
Labels: priority: 2 - normal, status: stalled, type: feature

#19 Fix Pipfile and add only required deps
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: priority: 2 - normal, status: needs review

#20 ADD CONTIBUTING.md
  CONTRIBUTING.md
Labels: priority: 2 - normal, type: feature

#27 Update readme
  README.md
Labels: priority: 3 - low, type: feature

#32 add shields to readme.md
  README.md
Labels: priority: 2 - normal, status: needs review

#37 Add Travis CI
  .github/CODEOWNERS
  .pre-commit-config.yaml
  .travis.yml
  Pipfile
  Pipfile.lock
  README.md
  flake8.cfg
  main.py
Labels: priority: 1 - high, status: needs review, type: feature

#21 Add pagination
  CONTRIBUTING.md
  Pipfile.lock
  cogs/utils/paginator.py
  main.py
Labels: priority: 2 - normal, status: stale, status: waiting for author, type: feature

#11 Standardize the code
  .gitignore
  .pre-commit-config.yaml
  .travis.yml
  Pipfile
  Pipfile.lock
  cogs/code_utils/_doc.py
  cogs/code_utils/_ref.py
  cogs/code_utils/_tio.py
  cogs/code_utils/_used.py
  cogs/codesandbox.py
  cogs/coding.py
  cogs/commands.py
  cogs/converters.py
  cogs/custom.py
  cogs/events.py
  cogs/fun.py
  cogs/games.py
  cogs/infog.py
  cogs/moderation.py
  cogs/study.py
  cogs/sudo.py
  cogs/support.py
  cogs/tools.py
  cogs/utils/constants.py
  cogs/utils/embedHandler.py
  cogs/utils/flags.py
  cogs/utils/paginator.py
  flake8.cfg
  main.py
  pyproject.toml
  utils/binarycalc.py
  utils/hexcalc.py
  utils/mathscrape.py
  utils/octcalc.py
  utils/wolframscrape.py
Labels: priority: 1 - high, status: waiting for author, type: feature

#41 Add dotenv support
  Pipfile
  cogs/sudo.py
  cogs/utils/constants.py
  main.py
  utils/wolframscrape.py
Labels: priority: 1 - high, status: waiting for author, type: feature

#26 Added some tools and updated the Old!
  cogs/custom.py
  cogs/tools.py
  cogs/utils/constants.py
  main.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#25 Add multiban and clear command
  cogs/moderation.py
  cogs/utils/formats.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#31 Add emotes support
  .gitignore
  cogs/emote_utils/emotes.py
  cogs/emote_utils/exceptions.py
  cogs/emotes.py
  main.py
Labels: priority: 2 - normal, status: needs review, type: feature

#34 add hangman
  assets/words.py
  cogs/games.py
Labels: priority: 2 - normal, status: needs review, type: feature

#24 Add urbandict support for dictionary.
  cogs/study.py
  cogs/tools.py
  cogs/urbandict_utils/urbandictpages.py
  cogs/utils/paginator.py
  main.py
Labels: priority: 2 - normal, status: stalled, type: feature

#22 Update events and Some code-compiler edits
  assets/checks.py
  cogs/codesandbox.py
  cogs/commands.py
  cogs/events.py
  cogs/games.py
  cogs/sudo.py
  cogs/utils/constants.py
  main.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#51 Add translation Features to Bot
  Pipfile
  Pipfile.lock
  cogs/translate.py
  main.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#52 Add xkcd comics
  cogs/fun.py
Labels: priority: 2 - normal, type: feature

#45 Renamed custom to common
  cogs/common.py
  main.py
Labels: priority: 3 - low, status: needs review, type: feature

#29 Initial Commit at some-changes
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  assets/checks.py
  assets/excuses.txt
  assets/words.py
  cogs/commands.py
  cogs/common.py
  cogs/converters.py
  cogs/endpoints/endpoints.py
  cogs/events.py
  cogs/fun.py
  cogs/games.py
  cogs/moderation.py
  cogs/search.py
  cogs/search_utils/regex.py
  cogs/search_utils/searchexceptions.py
  cogs/sudo.py
  cogs/support.py
  cogs/tools.py
  cogs/translate.py
  cogs/utils/constants.py
  cogs/utils/conversion.py
  cogs/utils/embed_handler.py
  cogs/utils/errors.py
  cogs/utils/paginator.py
  main.py
  pyproject.toml
Labels: priority: 2 - normal, status: needs review, type: feature

#58 Add Embed creator
  cogs/embeds.py
  flake8.cfg
  main.py
Labels: priority: 3 - low, status: needs review, type: feature

#38 Antimalware additions
  Pipfile
  Pipfile.lock
  assets/AntiMalware.py
  cogs/games.py
  cogs/malware_protection.py
  cogs/search.py
  cogs/utils/constants.py
  main.py
Labels: priority: 2 - normal, status: WIP, type: feature
