Repository Codin-Nerds/HotWired-Bot, pull requests merged in 2020-08, with the labels that each got.

#111 Fix failing azure pipelines checks
  .azure-pipelines.yaml
Labels: priority: 0 - critical, status: needs review, type: bug

#71 Add paste service in `common.py`
  bot/cogs/common.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#104 Add multiple converters
  Pipfile
  Pipfile.lock
  bot/cogs/codesandbox.py
  bot/cogs/common.py
  bot/cogs/fun.py
  bot/cogs/moderation.py
  bot/cogs/security.py
  bot/cogs/study.py
  bot/core/converters.py
  bot/core/decorators.py
  bot/utils/errors.py
  bot/utils/time.py
Labels: priority: 2 - normal, status: WIP, type: feature

#103 Clean up the coding cog
  bot/cogs/coding/coding.py
  bot/cogs/coding/documentation.py
  bot/cogs/coding/reference.py
  bot/cogs/coding/tiorun.py
  bot/cogs/coding/utility.py
  bot/config.py
Labels: priority: 2 - normal, status: WIP, type: feature

#101 Add trivia with proper questions
  Pipfile
  Pipfile.lock
  bot/cogs/games/__init__.py
  bot/cogs/games/trivia.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#83 Add logging
  .gitignore
  Pipfile
  Pipfile.lock
  bot/__init__.py
  bot/cogs/moderation.py
  bot/cogs/reddit.py
  bot/cogs/security.py
  bot/core/bot.py
  bot/core/converters.py
  bot/core/decorators.py
Labels: priority: 1 - high, status: WIP, type: feature

#94 Added Pokemon & Weather Commands
  bot/cogs/games/games.py
  bot/cogs/search.py
  bot/config.py
Labels: priority: 3 - low, status: waiting for author, type: feature

#67 Add Tic Tac Toe game
  bot/cogs/fun.py
  bot/cogs/games/__init__.py
  bot/cogs/games/tic_tac_toe.py
Labels: priority: 3 - low, status: needs review, type: feature

#82 Music commands
  Pipfile
  Pipfile.lock
  bot/cogs/music.py
  bot/cogs/search.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#80 Add animes features
  .azure-pipelines.yaml
  README.md
Labels: priority: 2 - normal, status: WIP, type: feature

#93 Added NSFW Commands
  bot/__main__.py
  bot/assets/nsfw_subreddit.json
  bot/cogs/disjobs.py
  bot/cogs/nsfw/__init__.py
  bot/cogs/nsfw/neko.py
  bot/cogs/nsfw/yandere.py
  bot/cogs/reddit.py
  bot/utils/jobfinder.py
Labels: priority: 3 - low, type: feature

#60 Add help system
  bot/__main__.py
  bot/cogs/help.py
  bot/config.py
  bot/core/bot.py
Labels: priority: 2 - normal, type: feature

#112 Move fun and comics to games
  bot/__main__.py
  bot/cogs/games/__init__.py
  bot/cogs/games/comics.py
  bot/cogs/games/fun.py
Labels: priority: 2 - normal, status: needs review, type: feature

#102 Fix basic code issues
  CONTRIBUTING.md
  bot/cogs/codesandbox.py
  bot/cogs/coding/__init__.py
  bot/cogs/coding/coding.py
  bot/cogs/coding/documentation.py
  bot/cogs/coding/reference.py
  bot/cogs/coding/tiorun.py
  bot/cogs/commands.py
  bot/cogs/common.py
  bot/cogs/conversion.py
  bot/cogs/disjobs.py
  bot/cogs/documentation.py
  bot/cogs/embeds.py
  bot/cogs/emotes.py
  bot/cogs/events.py
  bot/cogs/games/__init__.py
  bot/cogs/games/comics.py
  bot/cogs/games/fun.py
  bot/cogs/games/games.py
  bot/cogs/games/trivia.py
  bot/cogs/github.py
  bot/cogs/moderation.py
  bot/cogs/nasa.py
  bot/cogs/reddit.py
  bot/cogs/search.py
  bot/cogs/security.py
  bot/cogs/study.py
  bot/cogs/sudo.py
  bot/cogs/support.py
  bot/cogs/tools.py
  bot/cogs/translate.py
  bot/core/bot.py
  bot/core/converters.py
  bot/core/decorators.py
  bot/utils/checks.py
  bot/utils/formats.py
  bot/utils/jobfinder.py
  bot/utils/math.py
  bot/utils/paginator.py
  bot/utils/wolframscrape.py
  start.py
Labels: priority: 2 - normal, type: feature

#78 Add some more Fun games
  Pipfile.lock
  bot/cogs/games/games.py
  bot/config.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#72 Add 2 more fun commands
  bot/cogs/games/fun.py
  main.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#75 Regain everything back in FUN
  bot/cogs/coding/coding.py
  bot/cogs/coding/utility.py
  bot/cogs/study.py
  main.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#91 Add Prefixes that can be changed on a server basis
  bot/__main__.py
  bot/assets/prefixes.json
  bot/cogs/commands.py
  bot/cogs/events.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#116 initial bug fixes
  bot/__main__.py
  bot/assets/nsfw_subreddit.json
  bot/cogs/codesandbox.py
  bot/cogs/games/__init__.py
  bot/cogs/games/fun.py
  bot/cogs/games/trivia.py
  bot/cogs/github.py
  bot/cogs/nsfw/__init__.py
  bot/cogs/nsfw/nekos.py
  bot/cogs/nsfw/nsfw.py
  bot/cogs/nsfw/yandere.py
  bot/cogs/reddit.py
  bot/cogs/search.py
  bot/cogs/security.py
  bot/cogs/study.py
  bot/cogs/sudo.py
  bot/cogs/tools.py
  bot/cogs/translate.py
  bot/core/bot.py
  bot/utils/math.py
  bot/utils/wolframscrape.py
Labels: priority: 2 - normal, status: needs review, type: bug

#50 Games (connect4, blackjack)
  bot/cogs/games.py
Labels: priority: 3 - low, status: stale, status: waiting for author, type: feature

#113 Add birthday options for everyone, in bot
  bot/assets/bday.json
  bot/cogs/birthday.py
  bot/cogs/lock.py
Labels: priority: 2 - normal, status: waiting for author, type: feature
