Repository Codin-Nerds/HotWired-Bot, pull requests merged in 2020-07, with the labels that each got.

#48 Changes to main.py
  main.py
Labels: priority: 2 - normal, type: feature

#66 Add reddit support
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/assets/subreddit.json
  bot/cogs/reddit.py
  bot/cogs/translate.py
  bot/config.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#73 Add various sudo functionalities
  Pipfile
  Pipfile.lock
  bot/cogs/common.py
  bot/cogs/sudo.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#68 Add support features available
  bot/cogs/support.py
  bot/config.py
Labels: priority: 3 - low, type: feature

#59 GitHub integration
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/cogs/fun.py
  bot/cogs/github.py
  bot/config.py
Labels: priority: 3 - low, type: feature

#81 Docker
  .azure-pipelines.yaml
  .dockerignore
  .gitignore
  .pre-commit-config.yaml
  .travis.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/cogs/codesandbox.py
  bot/cogs/coding/coding.py
  bot/cogs/comics.py
  bot/cogs/reddit.py
  bot/cogs/sudo.py
  bot/cogs/translate.py
  bot/config.py
  bot/core/bot.py
  bot/core/converters.py
  bot/core/decorators.py
  bot/utils/checks.py
  docker-compose.yml
  flake8.cfg
  pyproject.toml
  tox.ini
Labels: priority: 2 - normal, status: needs review, type: feature

#85 Flake8 import order
  bot/cogs/codesandbox.py
  bot/cogs/coding/documentation.py
  bot/cogs/coding/reference.py
  bot/cogs/coding/utility.py
  bot/cogs/commands.py
  bot/cogs/common.py
  bot/cogs/conversion.py
  bot/cogs/documentation.py
  bot/cogs/embeds.py
  bot/cogs/emotes.py
  bot/cogs/events.py
  bot/cogs/fun.py
  bot/cogs/games/games.py
  bot/cogs/games/hangman.py
  bot/cogs/github.py
  bot/cogs/moderation.py
  bot/cogs/search.py
  bot/cogs/security.py
  bot/cogs/study.py
  bot/cogs/support.py
  bot/cogs/tools.py
  bot/config.py
  bot/utils/errors.py
  bot/utils/wolframscrape.py
  pyproject.toml
  tox.ini
Labels: priority: 2 - normal, status: needs review

#70 Add paste service to antimalware
  bot/cogs/events.py
  bot/cogs/security.py
  bot/config.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#69 Add nasa api commands
  bot/__main__.py
  bot/cogs/nasa.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#92 Remove flake8-import-order and install flake8-bugbear
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/cogs/codesandbox.py
  bot/cogs/coding/coding.py
  bot/cogs/coding/documentation.py
  bot/cogs/coding/reference.py
  bot/cogs/coding/tiorun.py
  bot/cogs/coding/utility.py
  bot/cogs/comics.py
  bot/cogs/commands.py
  bot/cogs/common.py
  bot/cogs/conversion.py
  bot/cogs/documentation.py
  bot/cogs/embeds.py
  bot/cogs/emotes.py
  bot/cogs/events.py
  bot/cogs/fun.py
  bot/cogs/games/games.py
  bot/cogs/games/hangman.py
  bot/cogs/github.py
  bot/cogs/moderation.py
  bot/cogs/nasa.py
  bot/cogs/reddit.py
  bot/cogs/search.py
  bot/cogs/security.py
  bot/cogs/study.py
  bot/cogs/sudo.py
  bot/cogs/support.py
  bot/cogs/tools.py
  bot/cogs/translate.py
  bot/config.py
  bot/core/bot.py
  bot/core/converters.py
  bot/core/decorators.py
  bot/utils/checks.py
  bot/utils/paginator.py
Labels: priority: 0 - critical, type: feature

#88 Added leetify command and improved docstrings
  bot/cogs/coding/tiorun.py
  bot/cogs/comics.py
  bot/cogs/commands.py
  bot/cogs/common.py
  bot/cogs/conversion.py
  bot/cogs/emotes.py
  bot/cogs/fun.py
  bot/cogs/games/games.py
  bot/cogs/games/hangman.py
  bot/cogs/github.py
  bot/cogs/nasa.py
  bot/cogs/search.py
Labels: priority: 3 - low, status: waiting for author, type: bug

#61 Update moderation commands
  bot/cogs/commands.py
  bot/cogs/embeds.py
  bot/cogs/events.py
  bot/cogs/moderation.py
  bot/cogs/sudo.py
  bot/utils/checks.py
Labels: priority: 2 - normal, status: waiting for author, type: feature
